"""initial control plane

Revision ID: 882998eacd77
Revises:
Create Date: 2026-08-24 23:18:47.844309
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "882998eacd77"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_keys",
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("prefix", sa.String(length=24), nullable=False),
        sa.Column("key_hash", sa.String(length=64), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_keys")),
        sa.UniqueConstraint("key_hash", name=op.f("uq_api_keys_key_hash")),
        sa.UniqueConstraint("name", name=op.f("uq_api_keys_name")),
    )
    op.create_index(op.f("ix_api_keys_is_active"), "api_keys", ["is_active"], unique=False)
    op.create_index(op.f("ix_api_keys_prefix"), "api_keys", ["prefix"], unique=False)
    op.create_table(
        "datasets",
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column(
            "dataset_type",
            sa.Enum("cpt", "sft", "evaluation", name="datasettype", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("validating", "ready", "invalid", name="datasetstatus", native_enum=False),
            nullable=False,
        ),
        sa.Column("file_name", sa.String(length=255), nullable=False),
        sa.Column("local_path", sa.String(length=1024), nullable=False),
        sa.Column("record_count", sa.Integer(), nullable=True),
        sa.Column("size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column("schema_summary", sa.JSON(), nullable=False),
        sa.Column("validation_errors", sa.JSON(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_datasets")),
        sa.UniqueConstraint("local_path", name=op.f("uq_datasets_local_path")),
    )
    op.create_index(op.f("ix_datasets_dataset_type"), "datasets", ["dataset_type"], unique=False)
    op.create_index(op.f("ix_datasets_name"), "datasets", ["name"], unique=False)
    op.create_index(op.f("ix_datasets_status"), "datasets", ["status"], unique=False)
    op.create_table(
        "gpu_leases",
        sa.Column("gpu_index", sa.Integer(), nullable=False),
        sa.Column("lease_group_id", sa.Uuid(), nullable=False),
        sa.Column(
            "owner_type",
            sa.Enum("deployment", "training", "evaluation", name="leaseownertype", native_enum=False),
            nullable=False,
        ),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("owner_name", sa.String(length=128), nullable=False),
        sa.Column("generation", sa.Integer(), nullable=False),
        sa.Column("acquired_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_gpu_leases")),
        sa.UniqueConstraint("gpu_index", name="uq_gpu_leases_gpu_index"),
        sa.UniqueConstraint(
            "owner_type",
            "owner_id",
            "gpu_index",
            name="uq_gpu_leases_owner_gpu",
        ),
    )
    op.create_index(op.f("ix_gpu_leases_expires_at"), "gpu_leases", ["expires_at"], unique=False)
    op.create_index(op.f("ix_gpu_leases_gpu_index"), "gpu_leases", ["gpu_index"], unique=False)
    op.create_index(op.f("ix_gpu_leases_heartbeat_at"), "gpu_leases", ["heartbeat_at"], unique=False)
    op.create_index(op.f("ix_gpu_leases_lease_group_id"), "gpu_leases", ["lease_group_id"], unique=False)
    op.create_index(op.f("ix_gpu_leases_owner_id"), "gpu_leases", ["owner_id"], unique=False)
    op.create_index(op.f("ix_gpu_leases_owner_type"), "gpu_leases", ["owner_type"], unique=False)
    op.create_table(
        "model_assets",
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column(
            "source_type",
            sa.Enum(
                "huggingface",
                "modelscope",
                "sftp",
                "manual",
                "trained",
                name="modelsourcetype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("source_uri", sa.String(length=1024), nullable=True),
        sa.Column("revision", sa.String(length=255), nullable=True),
        sa.Column("local_path", sa.String(length=1024), nullable=False),
        sa.Column(
            "model_kind",
            sa.Enum("base", "instruct", "embedding", name="modelkind", native_enum=False),
            nullable=False,
        ),
        sa.Column("format", sa.String(length=32), nullable=False),
        sa.Column(
            "status",
            sa.Enum("importing", "ready", "failed", name="assetstatus", native_enum=False),
            nullable=False,
        ),
        sa.Column("family", sa.String(length=128), nullable=True),
        sa.Column("parameter_count", sa.BigInteger(), nullable=True),
        sa.Column("size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("checksum", sa.String(length=128), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_assets")),
        sa.UniqueConstraint("local_path", name=op.f("uq_model_assets_local_path")),
    )
    op.create_index(op.f("ix_model_assets_name"), "model_assets", ["name"], unique=False)
    op.create_index(op.f("ix_model_assets_status"), "model_assets", ["status"], unique=False)
    op.create_table(
        "deployments",
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("served_model_name", sa.String(length=128), nullable=False),
        sa.Column("model_asset_id", sa.Uuid(), nullable=False),
        sa.Column(
            "task_type",
            sa.Enum("generate", "embedding", name="deploymenttasktype", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "desired_state",
            sa.Enum("running", "stopped", name="desiredservicestate", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "actual_state",
            sa.Enum(
                "created",
                "queued",
                "starting",
                "running",
                "stopping",
                "stopped",
                "failed",
                name="deploymentstate",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("gpu_ids", sa.JSON(), nullable=False),
        sa.Column("tensor_parallel_size", sa.Integer(), nullable=False),
        sa.Column("port", sa.Integer(), nullable=True),
        sa.Column("internal_url", sa.String(length=512), nullable=True),
        sa.Column("simplified_config", sa.JSON(), nullable=False),
        sa.Column("vllm_args", sa.JSON(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("queued_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("state_version", sa.Integer(), nullable=False),
        sa.Column("runtime_generation", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["model_asset_id"],
            ["model_assets.id"],
            name=op.f("fk_deployments_model_asset_id_model_assets"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_deployments")),
        sa.UniqueConstraint("name", name="uq_deployments_name"),
        sa.UniqueConstraint("port", name=op.f("uq_deployments_port")),
        sa.UniqueConstraint("served_model_name", name="uq_deployments_served_model_name"),
    )
    op.create_index(op.f("ix_deployments_actual_state"), "deployments", ["actual_state"], unique=False)
    op.create_index(op.f("ix_deployments_model_asset_id"), "deployments", ["model_asset_id"], unique=False)
    op.create_index(op.f("ix_deployments_queued_at"), "deployments", ["queued_at"], unique=False)
    op.create_index(
        op.f("ix_deployments_served_model_name"), "deployments", ["served_model_name"], unique=False
    )
    op.create_table(
        "evaluation_runs",
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("base_model_asset_id", sa.Uuid(), nullable=False),
        sa.Column("candidate_model_asset_id", sa.Uuid(), nullable=False),
        sa.Column("custom_dataset_id", sa.Uuid(), nullable=True),
        sa.Column("builtin_datasets", sa.JSON(), nullable=False),
        sa.Column(
            "desired_state",
            sa.Enum("running", "terminated", name="desiredjobstate", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "actual_state",
            sa.Enum(
                "created",
                "queued",
                "starting",
                "running",
                "canceling",
                "canceled",
                "succeeded",
                "failed",
                name="jobstate",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("gpu_ids", sa.JSON(), nullable=False),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.Column("comparison", sa.JSON(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("queued_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("state_version", sa.Integer(), nullable=False),
        sa.Column("runtime_generation", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["base_model_asset_id"],
            ["model_assets.id"],
            name=op.f("fk_evaluation_runs_base_model_asset_id_model_assets"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["candidate_model_asset_id"],
            ["model_assets.id"],
            name=op.f("fk_evaluation_runs_candidate_model_asset_id_model_assets"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["custom_dataset_id"],
            ["datasets.id"],
            name=op.f("fk_evaluation_runs_custom_dataset_id_datasets"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evaluation_runs")),
        sa.UniqueConstraint("name", name="uq_evaluation_runs_name"),
    )
    op.create_index(
        op.f("ix_evaluation_runs_actual_state"), "evaluation_runs", ["actual_state"], unique=False
    )
    op.create_index(
        op.f("ix_evaluation_runs_base_model_asset_id"),
        "evaluation_runs",
        ["base_model_asset_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_evaluation_runs_candidate_model_asset_id"),
        "evaluation_runs",
        ["candidate_model_asset_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_evaluation_runs_custom_dataset_id"), "evaluation_runs", ["custom_dataset_id"], unique=False
    )
    op.create_index(op.f("ix_evaluation_runs_queued_at"), "evaluation_runs", ["queued_at"], unique=False)
    op.create_table(
        "training_jobs",
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("model_asset_id", sa.Uuid(), nullable=False),
        sa.Column("dataset_id", sa.Uuid(), nullable=False),
        sa.Column("stage", sa.Enum("cpt", "sft", name="trainingstage", native_enum=False), nullable=False),
        sa.Column(
            "algorithm",
            sa.Enum("freeze", "lora", "qlora", name="trainingalgorithm", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "desired_state",
            sa.Enum("running", "terminated", name="desiredjobstate", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "actual_state",
            sa.Enum(
                "created",
                "queued",
                "starting",
                "running",
                "canceling",
                "canceled",
                "succeeded",
                "failed",
                name="jobstate",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("gpu_ids", sa.JSON(), nullable=False),
        sa.Column("progress", sa.Float(), nullable=False),
        sa.Column("current_step", sa.Integer(), nullable=True),
        sa.Column("total_steps", sa.Integer(), nullable=True),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.Column("training_config", sa.JSON(), nullable=False),
        sa.Column("output_dir", sa.String(length=1024), nullable=False),
        sa.Column("checkpoint_path", sa.String(length=1024), nullable=True),
        sa.Column("adapter_path", sa.String(length=1024), nullable=True),
        sa.Column("merged_model_path", sa.String(length=1024), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("queued_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("state_version", sa.Integer(), nullable=False),
        sa.Column("runtime_generation", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["datasets.id"],
            name=op.f("fk_training_jobs_dataset_id_datasets"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["model_asset_id"],
            ["model_assets.id"],
            name=op.f("fk_training_jobs_model_asset_id_model_assets"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_training_jobs")),
        sa.UniqueConstraint("name", name="uq_training_jobs_name"),
    )
    op.create_index(op.f("ix_training_jobs_actual_state"), "training_jobs", ["actual_state"], unique=False)
    op.create_index(op.f("ix_training_jobs_dataset_id"), "training_jobs", ["dataset_id"], unique=False)
    op.create_index(op.f("ix_training_jobs_queued_at"), "training_jobs", ["queued_at"], unique=False)
    op.create_index(
        op.f("ix_training_jobs_model_asset_id"), "training_jobs", ["model_asset_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_training_jobs_model_asset_id"), table_name="training_jobs")
    op.drop_index(op.f("ix_training_jobs_queued_at"), table_name="training_jobs")
    op.drop_index(op.f("ix_training_jobs_dataset_id"), table_name="training_jobs")
    op.drop_index(op.f("ix_training_jobs_actual_state"), table_name="training_jobs")
    op.drop_table("training_jobs")
    op.drop_index(op.f("ix_evaluation_runs_custom_dataset_id"), table_name="evaluation_runs")
    op.drop_index(op.f("ix_evaluation_runs_queued_at"), table_name="evaluation_runs")
    op.drop_index(op.f("ix_evaluation_runs_candidate_model_asset_id"), table_name="evaluation_runs")
    op.drop_index(op.f("ix_evaluation_runs_base_model_asset_id"), table_name="evaluation_runs")
    op.drop_index(op.f("ix_evaluation_runs_actual_state"), table_name="evaluation_runs")
    op.drop_table("evaluation_runs")
    op.drop_index(op.f("ix_deployments_served_model_name"), table_name="deployments")
    op.drop_index(op.f("ix_deployments_model_asset_id"), table_name="deployments")
    op.drop_index(op.f("ix_deployments_queued_at"), table_name="deployments")
    op.drop_index(op.f("ix_deployments_actual_state"), table_name="deployments")
    op.drop_table("deployments")
    op.drop_index(op.f("ix_model_assets_status"), table_name="model_assets")
    op.drop_index(op.f("ix_model_assets_name"), table_name="model_assets")
    op.drop_table("model_assets")
    op.drop_index(op.f("ix_gpu_leases_owner_type"), table_name="gpu_leases")
    op.drop_index(op.f("ix_gpu_leases_owner_id"), table_name="gpu_leases")
    op.drop_index(op.f("ix_gpu_leases_lease_group_id"), table_name="gpu_leases")
    op.drop_index(op.f("ix_gpu_leases_heartbeat_at"), table_name="gpu_leases")
    op.drop_index(op.f("ix_gpu_leases_gpu_index"), table_name="gpu_leases")
    op.drop_index(op.f("ix_gpu_leases_expires_at"), table_name="gpu_leases")
    op.drop_table("gpu_leases")
    op.drop_index(op.f("ix_datasets_status"), table_name="datasets")
    op.drop_index(op.f("ix_datasets_name"), table_name="datasets")
    op.drop_index(op.f("ix_datasets_dataset_type"), table_name="datasets")
    op.drop_table("datasets")
    op.drop_index(op.f("ix_api_keys_prefix"), table_name="api_keys")
    op.drop_index(op.f("ix_api_keys_is_active"), table_name="api_keys")
    op.drop_table("api_keys")
    # ### end Alembic commands ###
